#!/bin/bash

scriptName=$1
homeTrash=$HOME/trash
homeLog=$HOME/trash.log
homeCounter=$HOME/trash.counter

if [[ $# -ne 1 ]] 
then
	echo "There should be one parameter."
	exit 1
fi

if [[ ! -f $scriptName ]]
then
	echo "File must be exists"
	exit 1
fi

if [[ ! -d $homeTrash ]]
then 
	mkdir $homeTrash
	touch $homeLog
	touch $homeCounter
	echo "0" > $homeCounter
fi

count=$(($(cat $homeCounter) + 1))

ln $scriptName $homeTrash/$count
rm $scriptName

echo "$count:$(pwd):$scriptName" >> $homeLog
echo $count > $homeCounter
