#!/bin/bash

trash=$HOME/trash
log=$HOME/trash.log
restFile=$HOME/lab5/$1

if [[ $# -ne 1 ]]
then
	echo "There should be one parameter."
	exit 1
fi 

for i in $(grep -s $1 $log)
do
	count=$(echo $i | awk -F ':' '{print $1}')
	path=$(echo $i | awk -F ':' '{print $2}')
	name=$(echo $i | awk -F ':' '{print $3}')
	rmFile=$trash/$count
	if [[ -e $rmFile ]]
	then
		echo "Do you want to restore file - $path/$name ? (y/n)"
		read answer
		if [[ $answer == "y" ]]
		then
			if [[ -d $(dirname $path/$name) ]]
			then
				if [[ -e $path/$name ]]
				then
					echo "File already exists."
					rm $rmFile
					exit 0
				fi
				ln $rmFile $path/$name
			else
				echo "$(dirname $path/$name) has been removed!"
				ln $rmFile $HOME/$1
			fi
			rm $rmFile
		fi
	fi
done
