#!/bin/bash

trash=$HOME/trash
log=$HOME/trash.log

if [[ $# -ne 1 ]]
then
	echo "There should be one parameter."
	exit 1
fi

if [[ ! -d $trash ]]
then
	echo "Trash does not exists."
	exit 1
fi

for f in $(grep -sh $1 $log)
do
	count=$(echo $f | awk -F ':' '{print $1}')
	path=$(echo $f | awk -F ':' '{print $2}')
	name=$(echo $f | awk -F ':' '{print $3}')

	if [[ ! -e "$trash/$count" ]]
	then
		continue
	fi

	echo "Restore this file? (y/n) $path/$name"
	read answer

	if [[ "$answer" == "y" ]]
	then
		if [[ ! -d $path ]]
		then
			echo "Restore path does not exists anymore. Restoring to the home directory..."
			path=$HOME
		fi

		while [[ -e "$path/$name" ]]
		do
			echo "File already exists. Enter new filename."
			read name
		done

		ln "$trash/$count" "$path/$name"
		exit 0
	fi
done

echo "Nothing restored"
