#!/bin/bash

> v_problem

while true 
do 
	read s
	echo "$s" >> v_problem
	
	if [[ "$s" == "QUIT" ]]
	then 
		exit 0
	fi

	if [[ ! "$s" =~ [0-9]+ && "$s" != "+" && "$s" != "*" ]] 
	then 
		echo "Incorrect message"
		exit 1
	fi
done
